FROM ubuntu:trusty

MAINTAINER Yury Kotov <bairkan@yandex.ru>

RUN sudo apt-get install --yes vim-nox tmux samba git-core build-essential libssl-dev libcurl4-openssl-dev libreadline-dev curl ack-grep ctags libxslt-dev libxml2-dev
